
name: CI  # -- Tells the information about the pipeline e.g Terraform-Workflow

# Controls when the workflow will run
on:      # which decides when this workflowwith run
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" or "feature/103" ] #--- When anyone code commits to main branch

  pull_request:
    branches: [ "main" ] # --- #--- When anyone raise the Pull request to main branch or feature branch
    # If everyone working on the same feature  --feature/HclInfra-Deploy
                                                # feature /Hcl-Infra build

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # Git Hub servers (managed by git or self managed or runners)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   # AzureCli@2 / terraformCLI@4
               
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4      # Azure devops )(-task)

      # Runs a single command using the runners shell
      - name: Run a one-line script  # display Name
        run: echo Hello, world!  # called scripts in azure devops

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


          first github Actions
